services:
  db:
    image: postgres:16
    container_name: llm-tester-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: llm-eval
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d llm-eval"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./api
    container_name: llm-tester-api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/llm-eval
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"

  frontend:
    build: ./ui
    container_name: llm-tester-ui
    environment:
      BASE_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"

volumes:
  db_data: